### ISSUE TITLE
Наскрапить датасет с породами собак.

### ISSUE THREAD

**Issue by comratvlad** [ALVirtualTech/OnlinePetSearchService#11]
Отправная точка нашего датасета - соревнование Dog Breed Identification - https://www.kaggle.com/c/dog-breed-identification. "Словарь" пород содержит 120 классов, каждый их которых необходимо расширить хотя бы на 100-200 сэмплов (больше - лучше). Для начала это можно сделать при помощи библиотеки для скрапинга с google images - https://github.com/hardikvasa/google-images-download. В директории с проектом, в папке data необходимо создать папку images, в которой, для каждой из 120-ти пород также создать свою папку. В каждой такой папке и будут помещаться фотографии с собачками. Разметку необходимо хранить в директории data/labels.csv по примеру того, как это сделано в соревновании.

**Comment by comratvlad** [comment]
Код скрапера лучше всего оформить как python-скрипт и запушить в src/data_manipulation.

**Comment by comratvlad** [comment]
Результат сбора данных можно разместить в открытый доступ на Яндекс.диск/google.drive и поделиться ссылкой здесь либо в README проекта.

**Comment by Lara0Yu** [comment]
https://drive.google.com/open?id=1ZYeJkys9QFNRDHj_oEJb4ygMPA_afJ1E
ссылка на данные
