### ISSUE TITLE
Исследование возможностей различных фреймворков.

### ISSUE THREAD

**Issue by comratvlad** [ALVirtualTech/OnlinePetSearchService#4]
На данном этапе решили создать такую модель: клиент считает по входному видеопотоку дескрипторы, отправляет на сервер, где по нему ищется соответствие в базе. Соответственно вопрос: дают ли готовые фреймворки возможность получать дескрипторы по фотографиям лиц и если да, то какие? Если нет, то создать свою такую модель.

**Comment by a-poliakov** [comment]
задача откладывается, так как распознавание лиц для авторизации откладывается к следующему релизу, к распознаванию животных по фото отношения не имеет.
