### ISSUE TITLE
Обучение разработчика Алексея Кипреева

### ISSUE THREAD

**Issue by AVPGenium** [ALVirtualTech/OnlinePetSearchService#5]
Необходимо изучить:
- [ ] Java Core (уметь написать многопоточный код, правильно расставлять синхронизации и блокировки, уметь реализовывать код в ООП стиле, писать модульные тесты с JUnit)
- [ ] Научиться использовать git и github, работать с git из командной строки и из IDEA
- [ ] Изучить основы web-разработки на java (сервлеты, фильтры, сессии, куки,...)
- [ ] Научиться работать с базами данных (JDBC и изучить ORM Framework Hibernate + JPA + Spring Data JPA)
- [ ] Spring and DI/IoC, Spring Web + REST

**Comment by AVPGenium** [comment]
Основы веб-разработки на java:
https://stepik.org/course/146/syllabus

**Comment by Kenaitar** [comment]
Пройдено введение в ХТМЛ, продолжается знакомство с линуксом.

**Comment by Kenaitar** [comment]
Завершена первая глава курса по ХТМЛ. Сегодня начинаю вторую.

**Comment by Kenaitar** [comment]
Завершена вторая неделя. Завтра продолжу работать над третьей.

**Comment by Kenaitar** [comment]
Завершена вторая неделя. Завтра продолжу работать над третьей.

**Comment by Kenaitar** [comment]
Завершена третья неделя.

**Comment by a-poliakov** [comment]
истек срок актуальности задачи
